### ISSUE TITLE
Is there any specific reason why you diverged from the recommended client creation?

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/dotnet-aad-query-sample#2]
https://github.com/microsoftgraph/dotnet-aad-query-sample/blob/f455df455a98522e3af1819db48beb410cb558c2/MSGraphSamples.WPF/ViewModels/MainViewModel.cs#L111

See https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth

**Comment by Licantrop0** [comment]
fixed with #7 (using InteractiveAuthenticationProvider)
