### ISSUE TITLE
any specific reason why you diverged from recommended sdk usage? 

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/dotnet-aad-query-sample#3]
https://github.com/microsoftgraph/dotnet-aad-query-sample/blob/f455df455a98522e3af1819db48beb410cb558c2/MSGraphSamples.WPF/ViewModels/MainViewModel.cs#L125

See https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS

**Comment by Licantrop0** [comment]
it's because the SDK doesn't support Search and Count yet, so I preferred injecting the querystring parameters in one function for consistency.
When the new SDK will support that, I'll change to the recommended way by chaining `.Filter(...).OrderBy()`... etc..
